### PR TITLE
delete everything

### PR DESCRIPTION
**Pull request by notsuu**
ok

### CODE REVIEW

**Review by danii — APPROVED** [review]

**Review by WaviestBalloon — APPROVED** [review]

**Comment by ghost** [comment]
I approve

**Review by mellowmarshe — APPROVED** [review]

**Review by AlekEagle — CHANGES_REQUESTED** [review]
plagiarism of https://github.com/kelseyhightower/nocode

**Comment by notsuu** [comment]
unfortunately, i do not care

**Review by AlekEagle — APPROVED** [review]
author doesn't care, must not be important

**Comment by notsuu** [comment]
ok

**Comment by ghost** [comment]
i found an awful bug.... please fix it...
snip_016

**Comment by notsuu** [comment]
no

**Comment by AlekEagle** [comment]
language breaking bug, filing a CVE with a projected score of 10

**Comment by danii** [comment]
yell at #5

**Review by waydeb — APPROVED** [review]

**Comment by waydeb** [comment]
balls ( i meant to comment but shit balls (((())))))

**Comment by WaviestBalloon** [comment]
bal

**Comment by notsuu** [comment]
what is balls mean ? sory im 3 year old i don know these wors yet

**Comment by WaviestBalloon** [comment]
baller

**Comment by notsuu** [comment]
O.k. but what is baller means?

**Comment by notsuu** [comment]
> i found an awful bug.... please fix it... snip_016

It has been resolve

**Comment by WaviestBalloon** [comment]
no

**Comment by notsuu** [comment]
shut up

**Comment by coolshaurya** [comment]
lmfao

**Comment by danii** [comment]
unfortunately, the

**Review by ghost — APPROVED** [review]
'

**Comment by WaviestBalloon** [comment]
.

**Review by WaviestBalloon — APPROVED** [review]

**Comment by danii** [comment]
ten reactions on this comment and i merge

**Review by WaviestBalloon — CHANGES_REQUESTED** [review]
Add README

**Comment by AlekEagle** [comment]
The addition of a README would negate the reason this pull request was made

**Comment by WaviestBalloon** [comment]
Yes

**Comment by notsuu** [comment]
> Add README

No

**Comment by WaviestBalloon** [comment]
If the requested changes are not met then the PR cannot be merged

**Comment by notsuu** [comment]
No you must merg

**Comment by notsuu** [comment]
Why do you care about a literal markdown file

**Comment by notsuu** [comment]
@WaviestBalloon Does this satisfy you now

**Comment by danii** [comment]
image

**Comment by WaviestBalloon** [comment]
Yes

**Comment by notsuu** [comment]
Ok awesome i hope the experience delivered was a great👍👍

**Comment by WaviestBalloon** [comment]
It was a great great

**Comment by ghost** [comment]
this pr has greatly improved my workflow. i will be forever grateful for your contribution

**Comment by notsuu** [comment]
sorry

**Comment by waydeb** [comment]
wild this still exists

**Comment by waydeb** [comment]
react to this if

**Comment by notsuu** [comment]
rest in piece fofl12

**Comment by WaviestBalloon** [comment]
if

**Pull request merged**
